name: Wheels

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9a-z]+"

permissions:
  contents: read

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # NOTE: this should not be recursive, we really don't want to bundle vcpkg
          submodules: true

      - name: Build SDist
        run: pipx run build --sdist

      - name: Check metadata
        run: pipx run twine check dist/*

      - uses: actions/upload-artifact@v4
        with:
          name: dist-sdist
          path: dist/*.tar.gz

  generate_matrix:
    name: Generate OS matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.script.outputs.matrix }}
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Run python matrix script
        id: script
        run: |
          echo "matrix=$(python - <<EOF
          # XXX: final setup, to be enabled later (once everything actually works)
          # single = ["macos-15-intel", "macos-latest", "windows-latest", "windows-11-arm"]
          # ubuntu_archs = {
          #     "ubuntu-latest": ["native", "ppc64le", "s390x", "riscv64"],
          #     "ubuntu-24.04-arm": ["native"],
          # }
          single = ["windows-latest", "macos-latest"]
          ubuntu_archs = {"ubuntu-latest": ["native"]}
          # this will be the only one for now
          crypto = ["openssl_3"]

          matrix = []

          # simple os, nothing fancy
          for os in single:
              matrix += [{"os": os}]

          # linux runs on multiple archs and with/without musl
          for os, archs in ubuntu_archs.items():
              for arch in archs:
                  for libc in ["glibc", "musl"]:
                      matrix += [{"os": os, "arch": arch, "libc": libc}]

          # mix in crypto libraries into every entry
          matrix = [{**m, "crypto": c} for m in matrix for c in crypto]

          # add display names, these are just for displaying on GitHub
          for m in matrix:
              m["display-name"] = ", ".join(filter(None, [
                  m["os"], m.get("arch"), m.get("libc")
              ]))
              # why on earth does GHA not have a `replace()` function
              m["artifact-tag"] = m["display-name"].replace(", ", "-")

          import json
          print(json.dumps(matrix))
          EOF
          )" >> $GITHUB_OUTPUT

  build_wheels:
    name: Wheels (${{ matrix.display-name }})
    runs-on: ${{ matrix.os }}
    needs: generate_matrix
    strategy:
      fail-fast: false
      matrix:
        # entries are {os: *, arch: *, libc: *, crypto: *, display-name: *, artifact-tag: *}
        include: ${{ fromJSON(needs.generate_matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Unshallow vcpkg submodule
        run: git -C libdave/cpp/vcpkg fetch --unshallow

      - uses: ./.github/actions/prepare-vcpkg
        with:
          os-arch-key: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.libc }}
          crypto: ${{ matrix.crypto }}
          cache-dir: ${{ github.workspace }}/vcpkg_cache

      - name: Set up QEMU
        if: runner.os == 'Linux' && matrix.arch != 'native'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - uses: pypa/cibuildwheel@v3.2
        env:
          # choose manylinux/musllinux (they are split for the sake of ci speedup)
          CIBW_BUILD: ${{ matrix.libc == 'glibc' && '*manylinux*' || (matrix.libc == 'musl' && '*musllinux*' || '') }}
          CIBW_ARCHS: ${{ matrix.arch }}

      # TODO: add another step to fail CI if .pyi changed in wheels?
      - name: Verify clean directory
        run: git diff --exit-code -- ":^src/**/*.pyi"

      - name: Upload wheels
        uses: actions/upload-artifact@v5
        with:
          path: wheelhouse/*.whl
          name: dist-${{ matrix.artifact-tag }}

  release_github:
    name: Release GitHub
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs:
      - build_sdist
      - build_wheels
    runs-on: ubuntu-latest
    permissions:
      contents: write  # required for creating releases

    steps:
      - uses: actions/download-artifact@v5
        with:
          path: dist
          pattern: dist-*
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b  # v2.5.0
        with:
          files: dist/*
          draft: true
          body: |
            TBD

            **Changelog**: https://github.com/${{ github.repository }}/blob/main/docs/CHANGELOG.md#vTODO
            **Git history**: https://github.com/${{ github.repository }}/compare/vTODO...vTODO

  release_pypi:
    name: Release PyPI
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs:
      - build_sdist
      - build_wheels
    runs-on: ubuntu-latest

    environment:
      name: release-pypi
    permissions:
      id-token: write  # this permission is mandatory for trusted publishing

    steps:
      - uses: actions/setup-python@v6
      - uses: actions/download-artifact@v5
        with:
          path: dist
          pattern: dist-*
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e  # v1.13.0
        with:
          repository-url: https://test.pypi.org/legacy/
