name: Wheels

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Build SDist
        run: pipx run build --sdist

      - name: Check metadata
        run: pipx run twine check dist/*

      - uses: actions/upload-artifact@v4
        with:
          name: dist-sdist
          path: dist/*.tar.gz

  generate_matrix:
    name: Generate OS matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.script.outputs.matrix }}
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Run python matrix script
        id: script
        run: |
          echo "matrix=$(python - <<EOF
          # XXX: final setup, to be enabled later (once everything actually works)
          # single = ["macos-15-intel", "macos-latest", "windows-latest", "windows-11-arm"]
          # ubuntu_archs = {
          #     "ubuntu-latest": ["native", "ppc64le", "s390x", "riscv64"],
          #     "ubuntu-24.04-arm": ["native", "armv7l"],
          # }
          single = ["windows-latest"]
          ubuntu_archs = {"ubuntu-latest": ["native"]}
          # this will be the only one for now, but left configurable nonetheless
          # TODO: actually use this for VCPKG_MANIFEST_DIR
          crypto = ["openssl_3"]

          matrix = []

          # simple os, nothing fancy
          for os in single:
              matrix += [{"os": os}]

          # linux runs on multiple archs and with/without musl
          for os, archs in ubuntu_archs.items():
              for arch in archs:
                  for libc in ["glibc", "musl"]:
                      matrix += [{"os": os, "arch": arch, "libc": libc}]

          # mix in crypto libraries into every entry
          matrix = [{**m, "crypto": c} for m in matrix for c in crypto]

          # add display names, these are just for displaying on GitHub
          for m in matrix:
              m["display_name"] = ", ".join(filter(None, [
                  m["os"], m.get("arch"), m.get("libc")
              ]))

          import json
          print(json.dumps(matrix))
          EOF
          )" >> $GITHUB_OUTPUT

  build_wheels:
    name: Wheels (${{ matrix.display_name }})
    runs-on: ${{ matrix.os }}
    needs: generate_matrix
    strategy:
      fail-fast: false
      matrix:
        # entries are {os: *, arch: *, libc: *, crypto: *}
        include: ${{ fromJSON(needs.generate_matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      # TODO: this is somewhat expensive. maybe we can drop the vcpkg submodule somehow?
      - name: Unshallow vcpkg submodule
        run: git -C libdave/cpp/vcpkg fetch --unshallow

      - uses: ./.github/actions/prepare-vcpkg
        with:
          os-arch-key: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.libc }}
          crypto: ${{ matrix.crypto }}
          cache-dir: ${{ github.workspace }}/vcpkg_cache

      - name: Set up QEMU
        # armv7l can run natively on arm64v8, no qemu needed
        if: runner.os == 'Linux' && matrix.arch != 'native' && matrix.arch != 'armv7l'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      # TODO: CMAKE_BUILD_PARALLEL_LEVEL ?
      # TODO: REQUIRE_BORINGSSL to enforce boringssl if requested?
      - uses: pypa/cibuildwheel@v3.2
        env:
          # choose manylinux/musllinux (they are split for the sake of ci speedup)
          CIBW_BUILD: ${{ matrix.libc == 'glibc' && '*manylinux*' || (matrix.libc == 'musl' && '*musllinux*' || '') }}
          CIBW_ARCHS: ${{ matrix.arch }}

      - name: Verify clean directory
        run: git diff --exit-code

      - name: Upload wheels
        uses: actions/upload-artifact@v5
        with:
          path: wheelhouse/*.whl
          name: dist-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.libc }}

  upload_all:
    name: Upload if release
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - uses: actions/setup-python@v6
      - uses: actions/download-artifact@v5
        with:
          path: dist
          pattern: dist-*
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
